spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chamalwr/spring-configs
          default-label: main
          search-paths:
            -'*service'
server:
  port: 8191
